// <auto-generated />
using System;
using LibrarySystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LibrarySystem.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260512140654_ReservationApprovalFlow")]
    partial class ReservationApprovalFlow
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LibrarySystem.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("AvailableCopies")
                        .HasColumnType("int");

                    b.Property<string>("CategoryId")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("CoverImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("PublishedYear")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("TotalCopies")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Robert C. Martin",
                            AvailableCopies = 5,
                            CategoryId = "programming",
                            Description = "A handbook of agile software craftsmanship",
                            ISBN = "978-0132350884",
                            PublishedYear = 2008,
                            Title = "Clean Code",
                            TotalCopies = 5
                        },
                        new
                        {
                            Id = 2,
                            Author = "Andrew Hunt",
                            AvailableCopies = 3,
                            CategoryId = "programming",
                            Description = "Your journey to mastery",
                            ISBN = "978-0201616224",
                            PublishedYear = 1999,
                            Title = "The Pragmatic Programmer",
                            TotalCopies = 3
                        },
                        new
                        {
                            Id = 3,
                            Author = "Steve McConnell",
                            AvailableCopies = 2,
                            CategoryId = "programming",
                            Description = "A practical handbook of software construction",
                            ISBN = "978-0735619678",
                            PublishedYear = 2004,
                            Title = "Code Complete",
                            TotalCopies = 2
                        },
                        new
                        {
                            Id = 4,
                            Author = "Douglas Crockford",
                            AvailableCopies = 8,
                            CategoryId = "programming",
                            Description = "Uncovering the beauty of JavaScript",
                            ISBN = "978-0596517748",
                            PublishedYear = 2008,
                            Title = "JavaScript: The Good Parts",
                            TotalCopies = 8
                        },
                        new
                        {
                            Id = 5,
                            Author = "Eric Freeman",
                            AvailableCopies = 4,
                            CategoryId = "programming",
                            Description = "A brain-friendly guide",
                            ISBN = "978-0596007126",
                            PublishedYear = 2004,
                            Title = "Head First Design Patterns",
                            TotalCopies = 4
                        },
                        new
                        {
                            Id = 6,
                            Author = "Thomas H. Cormen",
                            AvailableCopies = 0,
                            CategoryId = "programming",
                            Description = "The comprehensive algorithms textbook",
                            ISBN = "978-0262033848",
                            PublishedYear = 2009,
                            Title = "Introduction to Algorithms",
                            TotalCopies = 0
                        },
                        new
                        {
                            Id = 7,
                            Author = "Ben Forta",
                            AvailableCopies = 3,
                            CategoryId = "database",
                            Description = "Sams teach yourself SQL in 10 minutes",
                            ISBN = "978-0672336079",
                            PublishedYear = 2020,
                            Title = "SQL in 10 Minutes",
                            TotalCopies = 3
                        },
                        new
                        {
                            Id = 8,
                            Author = "Abraham Silberschatz",
                            AvailableCopies = 2,
                            CategoryId = "database",
                            Description = "The definitive database textbook",
                            ISBN = "978-0073523325",
                            PublishedYear = 2019,
                            Title = "Database System Concepts",
                            TotalCopies = 2
                        },
                        new
                        {
                            Id = 9,
                            Author = "Pramod J. Sadalage",
                            AvailableCopies = 1,
                            CategoryId = "database",
                            Description = "A brief guide to the emerging world of polyglot persistence",
                            ISBN = "978-0321826626",
                            PublishedYear = 2012,
                            Title = "NoSQL Distilled",
                            TotalCopies = 1
                        },
                        new
                        {
                            Id = 10,
                            Author = "Andrew S. Tanenbaum",
                            AvailableCopies = 4,
                            CategoryId = "networking",
                            Description = "A top-down approach",
                            ISBN = "978-0133594140",
                            PublishedYear = 2020,
                            Title = "Computer Networking",
                            TotalCopies = 4
                        },
                        new
                        {
                            Id = 11,
                            Author = "W. Richard Stevens",
                            AvailableCopies = 2,
                            CategoryId = "networking",
                            Description = "The protocols",
                            ISBN = "978-0201633467",
                            PublishedYear = 1994,
                            Title = "TCP/IP Illustrated",
                            TotalCopies = 2
                        },
                        new
                        {
                            Id = 12,
                            Author = "Jon Duckett",
                            AvailableCopies = 6,
                            CategoryId = "web-development",
                            Description = "A visual guide to HTML and CSS",
                            ISBN = "978-1118008188",
                            PublishedYear = 2011,
                            Title = "HTML & CSS: Design and Build Websites",
                            TotalCopies = 6
                        },
                        new
                        {
                            Id = 13,
                            Author = "Stoyan Stefanov",
                            AvailableCopies = 0,
                            CategoryId = "web-development",
                            Description = "Building web applications",
                            ISBN = "978-1491931824",
                            PublishedYear = 2016,
                            Title = "React: Up and Running",
                            TotalCopies = 0
                        },
                        new
                        {
                            Id = 14,
                            Author = "Daniel Khalil",
                            AvailableCopies = 3,
                            CategoryId = "web-development",
                            Description = "Over 80 practical recipes",
                            ISBN = "978-1788996129",
                            PublishedYear = 2020,
                            Title = "Vue.js 3 Cookbook",
                            TotalCopies = 3
                        },
                        new
                        {
                            Id = 15,
                            Author = "Bill Phillips",
                            AvailableCopies = 2,
                            CategoryId = "mobile-development",
                            Description = "The big nerd ranch guide",
                            ISBN = "978-0135245125",
                            PublishedYear = 2019,
                            Title = "Android Programming: The Big Nerd Ranch Guide",
                            TotalCopies = 2
                        },
                        new
                        {
                            Id = 16,
                            Author = "Christian Keur",
                            AvailableCopies = 1,
                            CategoryId = "mobile-development",
                            Description = "The big nerd ranch guide",
                            ISBN = "978-0135594533",
                            PublishedYear = 2020,
                            Title = "iOS Programming: The Big Nerd Ranch Guide",
                            TotalCopies = 1
                        },
                        new
                        {
                            Id = 17,
                            Author = "Gene Kim",
                            AvailableCopies = 4,
                            CategoryId = "devops",
                            Description = "A novel about IT, DevOps, and helping your business win",
                            ISBN = "978-0988262506",
                            PublishedYear = 2013,
                            Title = "The Phoenix Project",
                            TotalCopies = 4
                        },
                        new
                        {
                            Id = 18,
                            Author = "Google SRE Team",
                            AvailableCopies = 2,
                            CategoryId = "devops",
                            Description = "How Google runs production systems",
                            ISBN = "978-1491929124",
                            PublishedYear = 2016,
                            Title = "Site Reliability Engineering",
                            TotalCopies = 2
                        },
                        new
                        {
                            Id = 19,
                            Author = "Aurelien Geron",
                            AvailableCopies = 3,
                            CategoryId = "data-science",
                            Description = "Scikit-Learn, Keras, and TensorFlow",
                            ISBN = "978-1492032632",
                            PublishedYear = 2019,
                            Title = "Hands-On Machine Learning",
                            TotalCopies = 3
                        },
                        new
                        {
                            Id = 20,
                            Author = "Joel Grus",
                            AvailableCopies = 0,
                            CategoryId = "data-science",
                            Description = "First principles with Python",
                            ISBN = "978-1492041139",
                            PublishedYear = 2019,
                            Title = "Data Science from Scratch",
                            TotalCopies = 0
                        },
                        new
                        {
                            Id = 21,
                            Author = "Dafydd Stuttard",
                            AvailableCopies = 2,
                            CategoryId = "security",
                            Description = "Finding and exploiting security flaws",
                            ISBN = "978-1118026470",
                            PublishedYear = 2011,
                            Title = "The Web Application Hacker's Handbook",
                            TotalCopies = 2
                        },
                        new
                        {
                            Id = 22,
                            Author = "Justin Seitz",
                            AvailableCopies = 1,
                            CategoryId = "security",
                            Description = "Python programming for hackers and pentesters",
                            ISBN = "978-1593275902",
                            PublishedYear = 2014,
                            Title = "Black Hat Python",
                            TotalCopies = 1
                        },
                        new
                        {
                            Id = 23,
                            Author = "Erich Gamma et al.",
                            AvailableCopies = 5,
                            CategoryId = "software-engineering",
                            Description = "Elements of reusable object-oriented software",
                            ISBN = "978-0201633610",
                            PublishedYear = 1994,
                            Title = "Design Patterns",
                            TotalCopies = 5
                        },
                        new
                        {
                            Id = 24,
                            Author = "Martin Fowler",
                            AvailableCopies = 3,
                            CategoryId = "software-engineering",
                            Description = "Improving the design of existing code",
                            ISBN = "978-0201485677",
                            PublishedYear = 1999,
                            Title = "Refactoring",
                            TotalCopies = 3
                        });
                });

            modelBuilder.Entity("LibrarySystem.Models.BorrowTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<DateTime>("BorrowDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ReturnDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("UserId");

                    b.ToTable("BorrowTransactions");
                });

            modelBuilder.Entity("LibrarySystem.Models.Category", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = "programming",
                            Description = "Books on programming languages and software development",
                            Name = "Programming"
                        },
                        new
                        {
                            Id = "database",
                            Description = "Database management and SQL books",
                            Name = "Database"
                        },
                        new
                        {
                            Id = "networking",
                            Description = "Computer networking and protocols",
                            Name = "Networking"
                        },
                        new
                        {
                            Id = "web-development",
                            Description = "Web design and web application development",
                            Name = "Web Development"
                        },
                        new
                        {
                            Id = "mobile-development",
                            Description = "Mobile app development for iOS and Android",
                            Name = "Mobile Development"
                        },
                        new
                        {
                            Id = "devops",
                            Description = "DevOps and site reliability engineering",
                            Name = "DevOps"
                        },
                        new
                        {
                            Id = "data-science",
                            Description = "Data science, machine learning, and AI",
                            Name = "Data Science"
                        },
                        new
                        {
                            Id = "security",
                            Description = "Cybersecurity and ethical hacking",
                            Name = "Security"
                        },
                        new
                        {
                            Id = "software-engineering",
                            Description = "Software engineering principles and practices",
                            Name = "Software Engineering"
                        });
                });

            modelBuilder.Entity("LibrarySystem.Models.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ClaimDeadline")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ClaimedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ReservationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("UserId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("LibrarySystem.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Course")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("IdNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<string>("MembershipTier")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfilePictureUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("YearLevel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = "admin-seed-id-001",
                            Course = "N/A",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@library.com",
                            FullName = "System Administrator",
                            IdNumber = "ADMIN001",
                            IsActive = true,
                            IsAdmin = true,
                            IsVerified = true,
                            MembershipTier = "Admin",
                            PasswordHash = "$2b$11$5Nv71ylXSG5plFrlGUwd/.8xkefOOMhcEQ/qHhiVnG9WuoQ72vBdu",
                            ProfilePictureUrl = "https://ui-avatars.com/api/?name=Admin&background=dc3545&color=fff&size=80",
                            UserName = "admin",
                            YearLevel = "N/A"
                        },
                        new
                        {
                            Id = "student-seed-id-001",
                            Course = "Computer Science",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "john.doe@university.edu",
                            FullName = "John Doe",
                            IdNumber = "20210001",
                            IsActive = true,
                            IsAdmin = false,
                            IsVerified = true,
                            MembershipTier = "Gold Member",
                            PasswordHash = "$2b$11$3kmO0B3kYPvG1QHXrRmKsel64iSCPAKO5UCtdWHlehQIReJp4NULe",
                            ProfilePictureUrl = "https://ui-avatars.com/api/?name=John+Doe&background=0d6efd&color=fff&size=80",
                            UserName = "johndoe",
                            YearLevel = "3rd Year"
                        });
                });

            modelBuilder.Entity("LibrarySystem.Models.Book", b =>
                {
                    b.HasOne("LibrarySystem.Models.Category", "Category")
                        .WithMany("Books")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("LibrarySystem.Models.BorrowTransaction", b =>
                {
                    b.HasOne("LibrarySystem.Models.Book", "Book")
                        .WithMany("BorrowTransactions")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibrarySystem.Models.User", "User")
                        .WithMany("BorrowTransactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LibrarySystem.Models.Reservation", b =>
                {
                    b.HasOne("LibrarySystem.Models.Book", "Book")
                        .WithMany("Reservations")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibrarySystem.Models.User", "User")
                        .WithMany("Reservations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LibrarySystem.Models.Book", b =>
                {
                    b.Navigation("BorrowTransactions");

                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("LibrarySystem.Models.Category", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("LibrarySystem.Models.User", b =>
                {
                    b.Navigation("BorrowTransactions");

                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
